name: Deployment
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 18.x
    - name: Install dependencies
      run: |
        cd sage
        composer install -o
        npm install
    - name: Build
      run: |
        cd sage
        npm run build
    
    - name: Sync
      env:
        dest: 'ubuntu@jagadeesh-wordpress.ddns.net:${{secrets.THEME_CONTENT}}'
      run: |
        echo "${{secrets.DEPLOY_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        rsync -cha --delete \
          -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
          --exclude /deploy_key \
          --exclude /.git/ \
          --exclude /.github/ \
          --exclude /node_modules/ \
          ./sage ${{env.dest}}

    - name: ssh and Deploy
      run: |
        echo "${{secrets.DEPLOY_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        ssh -i ./deploy_key ubuntu@jagadeesh-wordpress.ddns.net 'sudo docker cp ${{secrets.SOURCE_CONTENT}} wordpress:${{secrets.DOCKER_THEME_FOLDER}}'
